export const FETCH_ROLES_LIST_REQUEST = 'FETCH_ROLES_LIST_REQUEST';
export const FETCH_ROLES_LIST_SUCCESS = 'FETCH_ROLES_LIST_SUCCESS';
export const FETCH_ROLES_LIST_FAILURE = 'FETCH_ROLES_LIST_FAILURE';
