export const FETCH_POSTS_LIST_REQUEST = 'FETCH_POSTS_LIST_REQUEST';
export const FETCH_POSTS_LIST_SUCCESS = 'FETCH_POSTS_LIST_SUCCESS';
export const FETCH_POSTS_LIST_FAILURE = 'FETCH_POSTS_LIST_FAILURE';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';